export const HENTER_SYKMELDTE = 'HENTER_SYKMELDTE';
export const SYKMELDTE_HENTET = 'SYKMELDTE_HENTET';
export const HENT_SYKMELDTE_FEILET = 'HENT_SYKMELDTE_FEILET';
export const HENT_SYKMELDTE_FORESPURT = 'HENT_SYKMELDTE_FORESPURT';

export const VIS_LIGHTBOX = 'VIS_LIGHTBOX';
export const LUKK_LIGHTBOX = 'LUKK_LIGHTBOX';
