export const HENTER_SYKMELDTE = 'HENTER_SYKMELDTE';
export const SYKMELDTE_HENTET = 'SYKMELDTE_HENTET';
export const HENT_SYKMELDTE_FEILET = 'HENT_SYKMELDTE_FEILET';
export const HENT_SYKMELDTE_FORESPURT = 'HENT_SYKMELDTE_FORESPURT';
export const HENT_SYKMELDTE_BERIKELSER_FORESPURT = 'HENT_SYKMELDTE_BERIKELSER_FORESPURT';
export const HENTER_SYKMELDTE_BERIKELSER = 'HENTER_SYKMELDTE_BERIKELSER';
export const HENT_SYKMELDTE_BERIKELSER_FEILET = 'HENT_SYKMELDTE_BERIKELSER_FEILET';
export const SYKMELDTE_BERIKELSER_HENTET = 'SYKMELDTE_BERIKELSER_HENTET';

export const SLETT_SYKMELDT_FORESPURT = 'SLETT_SYKMELDT_FORESPURT';
export const SLETTER_SYKMELDT = 'SLETTER_SYKMELDT';
export const SYKMELDT_SLETTET = 'SYKMELDT_SLETTET';
export const SLETT_SYKMELDT_FEILET = 'SLETT_SYKMELDT_FEILET';

export const VIS_LIGHTBOX = 'VIS_LIGHTBOX';
export const LUKK_LIGHTBOX = 'LUKK_LIGHTBOX';

export const SET_SYKMELDTE_SORTERING = 'SET_SYKMELDTE_SORTERING';
