export const NAERMESTE_LEDER_LES_SOKNAD = 'NAERMESTE_LEDER_LES_SOKNAD';
export const NAERMESTE_LEDER_IKKE_SENDT_SYKEPENGESOKNAD = 'NAERMESTE_LEDER_IKKE_SENDT_SYKEPENGESOKNAD';
export const NAERMESTE_LEDER_DIALOGMOTE = 'NAERMESTE_LEDER_DIALOGMOTE';
export const NAERMESTE_LEDER_IKKE_SVART_MOTEBEHOV = 'NAERMESTE_LEDER_IKKE_SVART_MOTEBEHOV';
