export const TYPE_OPPFOLGINGSPLAN = 'TYPE_OPPFOLGINGSPLAN';
export const TYPE_SYKMELDING = 'TYPE_SYKMELDING';
export const TYPE_SYKEPENGESOKNAD = 'TYPE_SYKEPENGESOKNAD';
export const TYPE_DIALOGMOTE = 'TYPE_DIALOGMOTE';
export const TYPE_ALT = 'TYPE_ALT';
