export const eventNames = {
  aktivtReferat: 'Klikker på aktivt referat',
  behandlePersonopplysninger: 'Klikker på les mer om behandling av personopplysninger',
  brodsmule: 'Klikker på brødsmule',
  kontaktAndreMoter: 'Klikker på kontakt oss på andre måter',
  kontaktOss: 'Klikker på kontakt oss',
  lastNedReferat: 'Klikker på last ned referat',
  lenkeIReferat: 'Klikker på lenke i referat',
  lesMerOmDialogmoter: 'Klikker på les mer om dialogmøter',
  meldBehov: 'Klikker på meld behov',
  meldBehovKvittering: 'Klikker på kvittering meld behov',
  oppfolgingsplan: 'Klikker på oppfølgingsplan',
  seAvlysning: 'Klikker på se avlysning av innkalling',
  seEndring: 'Klikker på se endring av innkalling',
  seInnkalling: 'Klikker på se innkalling',
  sendMeldBehov: 'Klikker på send meld behov',
  sendSvarBehov: 'Klikker på send svar behov',
  svarBehov: 'Klikker på svar behov',
  svarBehovKvittering: 'Klikker på kvittering svar behov',
  tidligereReferat: 'Klikker på et tidligere referat',
  tidslinjen: 'Klikker på tidslinjen',
};
